/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;

import Doctor.Doctor;
import Login.Login;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Taneem
 */
public class Hospital extends javax.swing.JFrame {
private Frame frame;
    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtn_Update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtnDoctor = new javax.swing.JButton();
        jbtnAppointment = new javax.swing.JButton();
        jbtnPatient = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnPrescription = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtxtref = new javax.swing.JTextField();
        jtxtlot = new javax.swing.JTextField();
        jtxtissueddate = new javax.swing.JTextField();
        jtxtexpdate = new javax.swing.JTextField();
        jtxtdailydose = new javax.swing.JTextField();
        jtxtsideeffects = new javax.swing.JTextField();
        jtxtfurtherinfo = new javax.swing.JTextField();
        jtxtstorage = new javax.swing.JTextField();
        jtxtdriving = new javax.swing.JTextField();
        jtxthowtouse = new javax.swing.JTextField();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtDoctorNHS = new javax.swing.JTextField();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtPatientAdd = new javax.swing.JTextField();
        jComboTablets = new javax.swing.JComboBox();
        jtxtDoB = new javax.swing.JTextField();
        jtxttablets = new javax.swing.JTextField();
        jtxtdose = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtprescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1360, 860));
        setMinimumSize(new java.awt.Dimension(1360, 860));
        setPreferredSize(new java.awt.Dimension(1360, 860));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Hospital Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Prescription");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(217, 217, 217))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));

        jbtn_Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_Update.setText("UPDATE");
        jbtn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_UpdateActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbtnDoctor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDoctor.setText("DOCTOR");
        jbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoctorActionPerformed(evt);
            }
        });

        jbtnAppointment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnAppointment.setText("GP APPOINTMENT");
        jbtnAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAppointmentActionPerformed(evt);
            }
        });

        jbtnPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPatient.setText("PATIENT");
        jbtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatientActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("RESET");
        jbtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnResetMouseExited(evt);
            }
        });
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnPrescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPrescription.setText("PRESCRIPTION");
        jbtnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrescriptionActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("LOGIN");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("PRINT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setText("EXIT");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jbtn_Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnAppointment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnPrescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Update)
                    .addComponent(jButton2)
                    .addComponent(jbtnDoctor)
                    .addComponent(jbtnAppointment)
                    .addComponent(jbtnPatient)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnPrescription)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setPreferredSize(new java.awt.Dimension(1049, 518));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name of Tablets:");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Reference No.");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Dose (mg):");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Number of Tablets:");
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("LOT:");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Issued Date:");
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Exp. Date:");
        jLabel9.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Daily Dose:");
        jLabel10.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Possible Side Effects:");
        jLabel11.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Further Information:");
        jLabel12.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Storage Advice:");
        jLabel13.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Driving:");
        jLabel14.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("How to Use:");
        jLabel15.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Patient ID:");
        jLabel16.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("NHS NUmber:");
        jLabel17.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Patient Name:");
        jLabel18.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Date of Birth:");
        jLabel19.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Patient Address:");
        jLabel20.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtref.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtref.setPreferredSize(new java.awt.Dimension(200, 30));
        jtxtref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtrefActionPerformed(evt);
            }
        });

        jtxtlot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtlot.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtissueddate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtissueddate.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtexpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtexpdate.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtdailydose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtdailydose.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtsideeffects.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtsideeffects.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtfurtherinfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtfurtherinfo.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtstorage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtstorage.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtdriving.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtdriving.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxthowtouse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxthowtouse.setPreferredSize(new java.awt.Dimension(200, 30));
        jtxthowtouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxthowtouseActionPerformed(evt);
            }
        });

        jtxtPatientID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPatientID.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtDoctorNHS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDoctorNHS.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtPatientName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPatientName.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtPatientAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPatientAdd.setPreferredSize(new java.awt.Dimension(200, 30));

        jComboTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboTablets.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Make a selection", "Ibuprofen", "Co-Codamol", "Paracetamol", "Amlodopine" }));
        jComboTablets.setPreferredSize(new java.awt.Dimension(200, 30));
        jComboTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTabletsActionPerformed(evt);
            }
        });

        jtxtDoB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDoB.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxttablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxttablets.setPreferredSize(new java.awt.Dimension(200, 30));

        jtxtdose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtdose.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboTablets, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtissueddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtexpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtdailydose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtsideeffects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxttablets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxtdose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtref, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDoctorNHS, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtdriving, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtfurtherinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtstorage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxthowtouse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jtxtPatientAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTablets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtfurtherinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtstorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtref, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtdriving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtdose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxthowtouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxttablets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtissueddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDoctorNHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtexpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtdailydose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtsideeffects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPatientAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablets", "Reference No.", "Dose (mg)", "Number of Tablets", "LOT", "issued Date", "Exp. Date", "Daily Dose", "Possible Side Effects", "Further Information", "Storage Advice", "Driving and Using Medicines", "How to Use Medication", "Patient ID", "NHS Number", "Patient Name", "Date of Birth", "Patient Address"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jtxtprescription.setColumns(20);
        jtxtprescription.setRows(5);
        jScrollPane1.setViewportView(jtxtprescription);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow() == -1)
        {
            if(jTable1.getSelectedRowCount() == 0)
            {
                JOptionPane.showMessageDialog(null, "No Data to Delete", "Hospital Management Systems",
                    JOptionPane.OK_OPTION);
            }else
            {
                JOptionPane.showMessageDialog(null, "Select a row to Delete", "Hospital Management Systems",
                    JOptionPane.OK_OPTION);
            }
        }else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        frame = new Frame();
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit.","Hospital Management System",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try{
            jtxtprescription.print();   
        }catch(PrinterException ex){
            Logger.getLogger(Hospital.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTabletsActionPerformed
        if(jComboTablets.getSelectedItem().equals("Ibuprofen")){
            jtxtref.setText("Ibuprofen");
            jtxtdose.setText("2");
            jtxttablets.setText("32");
            jtxtlot.setText("561005875");
            jtxtissueddate.setText("06/05/2018");
            jtxtexpdate.setText("04/05/2019");
            jtxtdailydose.setText("4");
                    
            jtxtsideeffects.setText("Bleeding");
            jtxtfurtherinfo.setText("Place Dispensary");
            jtxtstorage.setText("Less Than 20%");
            jtxtdriving.setText("No");
            jtxthowtouse.setText("Use Water Only");
            jtxtPatientID.setText("P9589454");
            jtxtDoctorNHS.setText("646564");
        }
        else if(jComboTablets.getSelectedItem().equals("Co-Codamol")){
            jtxtref.setText("Co-Codamol");
            jtxtdose.setText("25");
            jtxttablets.setText("30");
            jtxtlot.setText("B770034");
            jtxtissueddate.setText("06/05/2018");
            jtxtexpdate.setText("04/12/2019");
            jtxtdailydose.setText("2");
                    
            jtxtsideeffects.setText("Dizziness");
            jtxtfurtherinfo.setText("Place Dispensary");
            jtxtstorage.setText("Less Than 20%");
            jtxtdriving.setText("No");
            jtxthowtouse.setText("Use Water, No Alcohol");
            jtxtPatientID.setText("P9589454");
            jtxtDoctorNHS.setText("646564");
        }
        else if(jComboTablets.getSelectedItem().equals("Paracetamol")){
            jtxtref.setText("Paracetamol");
            jtxtdose.setText("500");
            jtxttablets.setText("30");
            jtxtlot.setText("P02834");
            jtxtissueddate.setText("06/05/2019");
            jtxtexpdate.setText("04/12/2020");
            jtxtdailydose.setText("3");
                    
            jtxtsideeffects.setText("Filing Sick");
            jtxtfurtherinfo.setText("Place Dispensary");
            jtxtstorage.setText("Less Than 20%");
            jtxtdriving.setText("No");
            jtxthowtouse.setText("Use Water, No Alcohol");
            jtxtPatientID.setText("P95454");
            jtxtDoctorNHS.setText("646564");
        }
        else if(jComboTablets.getSelectedItem().equals("Amlodopine")){
            jtxtref.setText("Amlodopine");
            jtxtdose.setText("50");
            jtxttablets.setText("20");
            jtxtlot.setText("AM54034");
            jtxtissueddate.setText("06/05/2019");
            jtxtexpdate.setText("04/12/2020");
            jtxtdailydose.setText("2");
                    
            jtxtsideeffects.setText("Sleep");
            jtxtfurtherinfo.setText("Place Dispensary");
            jtxtstorage.setText("Less Than 20%");
            jtxtdriving.setText("No");
            jtxthowtouse.setText("Use Water, No Alcohol");
            jtxtPatientID.setText("As9454");
            jtxtDoctorNHS.setText("646564");
        }
        else if(jComboTablets.getSelectedItem().equals("Make a selection")){
            jtxtref.setText("");
            jtxtdose.setText("");
            jtxttablets.setText("");
            jtxtlot.setText("");
            jtxtissueddate.setText("");
            jtxtexpdate.setText("");
            jtxtdailydose.setText("");
                    
            jtxtsideeffects.setText("");
            jtxtfurtherinfo.setText("");
            jtxtstorage.setText("");
            jtxtdriving.setText("");
            jtxthowtouse.setText("");
            jtxtPatientID.setText("");
            jtxtDoctorNHS.setText("");
        }
        
    }//GEN-LAST:event_jComboTabletsActionPerformed

    private void jbtnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrescriptionActionPerformed
        String Qty1 = (jtxtref.getText());
        String Qty2 = (jtxtdose.getText());
        String Qty3 = (jtxttablets.getText());
        String Qty4 = (jtxtlot.getText());
        String Qty5 = (jtxtdailydose.getText());
        String Qty6 = (jtxtsideeffects.getText());
        String Qty7 = (jtxtfurtherinfo.getText());
        String Qty8 = (jtxthowtouse.getText());
        String Qty9 = (jtxtPatientID.getText());
        String Qty10 = (jtxtPatientName.getText());
        String Qty11 = (jtxtDoB.getText());
        String Qty12 = (jtxtPatientAdd.getText());
        String Qty13 = "";

        if(jComboTablets.getSelectedItem().equals("Ibuprofen"))
        {
            Qty13 = "Ibuprofen";
        }
        else if (jComboTablets.getSelectedItem().equals("Co-Codamol"))
        {
            Qty13 = "Co-Codamol";
        }
        else if (jComboTablets.getSelectedItem().equals("Paracetamol"))
        {
            Qty13 = "Paracetamol";
        }
        else if (jComboTablets.getSelectedItem().equals("Amlodopine"))
        {
            Qty13 = "Amlodopine";
        }

        jtxtprescription.setText("");
        jtxtprescription.append("\n\tHospital Management System\n\n"
            +"\nPatient Name:\t\t"+ Qty10
            +"\nDate of Birth:\t\t"+ Qty11
            +"\nPatient Address:\t"+ Qty12
            +"\nPrscription:\t\t"+ Qty13
            +"\n\n\nReference No.:\t\t"+ Qty1
            +"\nDose:\t\t"+ Qty2
            +"\nNumber of Tablets:\t"+ Qty3
            +"\nLoT:\t\t"+ Qty4
            +"\nDaily Dose:\t\t"+ Qty5
            +"\nPossible Side Effects:\t"+ Qty6
            +"\nFurther Information:\t"+ Qty7
            +"\nHow to Use Medicine:\t"+ Qty8
            +"\nPatient ID:\t\t"+ Qty9
            +"\n\n\n\n\n                       Patient Instruction we have introduced a \n\t          free text confirmation\n"
            +"                        TEXT REMINDERS FOR APPOINMENT");

        
    }//GEN-LAST:event_jbtnPrescriptionActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        
            jtxtref.setText("");
            jtxtdose.setText("");
            jtxttablets.setText("");
            jtxtlot.setText("");
            jtxtissueddate.setText("");
            jtxtexpdate.setText("");
            jtxtdailydose.setText("");
                    
            jtxtsideeffects.setText("");
            jtxtfurtherinfo.setText("");
            jtxtstorage.setText("");
            jtxtdriving.setText("");
            jtxthowtouse.setText("");
            jtxtPatientID.setText("");
            jtxtDoctorNHS.setText("");
            jtxtPatientName.setText("");
            jtxtDoB.setText("");
            jtxtPatientAdd.setText("");
            jtxtprescription.setText("");
            jComboTablets.getModel().setSelectedItem("Make a Selection");
        
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jbtn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_UpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{jComboTablets.getSelectedItem().toString(),
            jtxtref.getText(),jtxtdose.getText(),jtxttablets.getText(),
            jtxtlot.getText(),jtxtissueddate.getText(),jtxtexpdate.getText(),
            jtxtdailydose.getText(),jtxtsideeffects.getText(),jtxtfurtherinfo.getText(),
            jtxtstorage.getText(),jtxtdriving.getText(),jtxthowtouse.getText(),jtxtPatientID.getText(),
            jtxtDoctorNHS.getText(),jtxtPatientName.getText(),jtxtDoB.getText(),jtxtPatientAdd.getText(),});
    }//GEN-LAST:event_jbtn_UpdateActionPerformed

    private void jbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoctorActionPerformed
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_jbtnDoctorActionPerformed

    private void jbtnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAppointmentActionPerformed
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_jbtnAppointmentActionPerformed

    private void jbtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatientActionPerformed
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_jbtnPatientActionPerformed

    private void jtxtrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtrefActionPerformed

    private void jtxthowtouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxthowtouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxthowtouseActionPerformed

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        if (jButton10.isEnabled() == true) {
            jButton10.setBackground(Color.red);
            jButton10.setForeground(Color.black);
            //btn_equal.setFont(new Font(btn_equal.getFont().getName(),Font.BOLD,38));
        }
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        if (jButton10.isEnabled() == true) {
            jButton10.setBackground(new Color(204, 204, 204));
            //j_Login.setForeground(new Color(255, 153, 0));
            jButton10.setForeground(new Color(0, 0, 0));

        }
    }//GEN-LAST:event_jButton10MouseExited

    private void jbtnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnResetMouseEntered
        if (jbtnReset.isEnabled() == true) {
            jbtnReset.setBackground(Color.yellow);
            jbtnReset.setForeground(Color.black);
            //btn_equal.setFont(new Font(btn_equal.getFont().getName(),Font.BOLD,38));
        }
    }//GEN-LAST:event_jbtnResetMouseEntered

    private void jbtnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnResetMouseExited
        if (jbtnReset.isEnabled() == true) {
            jbtnReset.setBackground(new Color(204, 204, 204));
            //j_Login.setForeground(new Color(255, 153, 0));
            jbtnReset.setForeground(new Color(0, 0, 0));

        }
    }//GEN-LAST:event_jbtnResetMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboTablets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAppointment;
    private javax.swing.JButton jbtnDoctor;
    private javax.swing.JButton jbtnPatient;
    private javax.swing.JButton jbtnPrescription;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtn_Update;
    private javax.swing.JTextField jtxtDoB;
    private javax.swing.JTextField jtxtDoctorNHS;
    private javax.swing.JTextField jtxtPatientAdd;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextField jtxtdailydose;
    private javax.swing.JTextField jtxtdose;
    private javax.swing.JTextField jtxtdriving;
    private javax.swing.JTextField jtxtexpdate;
    private javax.swing.JTextField jtxtfurtherinfo;
    private javax.swing.JTextField jtxthowtouse;
    private javax.swing.JTextField jtxtissueddate;
    private javax.swing.JTextField jtxtlot;
    private javax.swing.JTextArea jtxtprescription;
    private javax.swing.JTextField jtxtref;
    private javax.swing.JTextField jtxtsideeffects;
    private javax.swing.JTextField jtxtstorage;
    private javax.swing.JTextField jtxttablets;
    // End of variables declaration//GEN-END:variables
}
