/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Doctor;

import java.awt.Frame;
import Login.Login;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Taneem
 */
public class Doctor extends javax.swing.JFrame {
private Frame frame;
    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jbtn_Update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtnDoctor = new javax.swing.JButton();
        jbtnAppointment = new javax.swing.JButton();
        jbtnPatient = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnPrescription = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jtxtSurName = new javax.swing.JTextField();
        jtxtMedical_Centre_Name = new javax.swing.JTextField();
        jtxtPatient_ID = new javax.swing.JTextField();
        jtxtCentre_Add = new javax.swing.JTextField();
        jtxtPost_Code = new javax.swing.JTextField();
        jtxtMedical_Centre_Ref = new javax.swing.JTextField();
        jtxtPhone1 = new javax.swing.JTextField();
        jtxtPhone2 = new javax.swing.JTextField();
        jtxtFax = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtPatient_NHS = new javax.swing.JTextField();
        jtxtEIMS_Number = new javax.swing.JTextField();
        jtxtGP_Appointment_ref = new javax.swing.JTextField();
        jtxtDoctor_NHS = new javax.swing.JTextField();
        jComboTablets = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1310, 850));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), null));

        jbtn_Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_Update.setText("UPDATE");
        jbtn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_UpdateActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbtnDoctor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDoctor.setText("PHARMACY");
        jbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoctorActionPerformed(evt);
            }
        });

        jbtnAppointment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnAppointment.setText("GP APPOINTMENT");
        jbtnAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAppointmentActionPerformed(evt);
            }
        });

        jbtnPatient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPatient.setText("PATIENT");
        jbtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatientActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("PAYMENT");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnPrescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPrescription.setText("PHARMACY OFFICE");
        jbtnPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrescriptionActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("LOGIN");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setText("EXIT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jbtn_Update)
                .addGap(15, 15, 15)
                .addComponent(jButton2)
                .addGap(15, 15, 15)
                .addComponent(jbtnDoctor)
                .addGap(15, 15, 15)
                .addComponent(jbtnAppointment)
                .addGap(15, 15, 15)
                .addComponent(jbtnPatient)
                .addGap(15, 15, 15)
                .addComponent(jbtnReset)
                .addGap(15, 15, 15)
                .addComponent(jbtnPrescription)
                .addGap(15, 15, 15)
                .addComponent(jButton8)
                .addGap(15, 15, 15)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_Update)
                    .addComponent(jButton2)
                    .addComponent(jbtnDoctor)
                    .addComponent(jbtnAppointment)
                    .addComponent(jbtnPatient)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnPrescription)
                    .addComponent(jButton8)
                    .addComponent(jButton10))
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Tablets", "Reference No.", "Dose (mg)", "Number of Tablets", "LOT", "issued Date", "Exp. Date", "Daily Dose", "Possible Side Effects", "Further Information", "Storage Advice", "Driving and Using Medicines", "How to Use Medication", "Patient ID", "NHS Number", "Patient Name", "Date of Birth", "Patient Address"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Doctor's Ref No.:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Doctor's NHS No.:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("First Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Surname:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Medical Centre Name:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Patient ID:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Address of Centre:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Post Code:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Medical Centre ref.:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Office Phone No. 1:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Office Phone No. 2:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Fax No.:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Email Address:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Patient's NHS NUmber:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("EMIS Number:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("GP Appointment Ref.:");

        jtxtFirstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtSurName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtMedical_Centre_Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtPatient_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPatient_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPatient_IDActionPerformed(evt);
            }
        });

        jtxtCentre_Add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtPost_Code.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtMedical_Centre_Ref.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtPhone1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtPhone2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtFax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtPatient_NHS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtEIMS_Number.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtGP_Appointment_ref.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtDoctor_NHS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jComboTablets.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboTablets.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Doctor's Ref.", "REZ10595", "KZ10472", "IK10474", "SS10597", "TI58741" }));
        jComboTablets.setMaximumSize(new java.awt.Dimension(300, 40));
        jComboTablets.setMinimumSize(new java.awt.Dimension(300, 40));
        jComboTablets.setPreferredSize(new java.awt.Dimension(300, 40));
        jComboTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTabletsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboTablets, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtxtMedical_Centre_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtxtSurName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPatient_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCentre_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtxtPost_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtDoctor_NHS, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMedical_Centre_Ref, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPatient_NHS, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEIMS_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtGP_Appointment_ref, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboTablets, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtMedical_Centre_Ref, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDoctor_NHS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSurName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jtxtMedical_Centre_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jtxtPatient_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jtxtCentre_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtPost_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jtxtPatient_NHS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jtxtEIMS_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jtxtGP_Appointment_ref, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addGap(43, 43, 43))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Doctor's Panel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_UpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{jComboTablets.getSelectedItem().toString(),
            jtxtDoctor_NHS.getText(),jtxtFirstName.getText(),jtxtSurName.getText(),
            jtxtMedical_Centre_Name.getText(),jtxtPatient_ID.getText(),jtxtCentre_Add.getText(),
            jtxtPost_Code.getText()/*,jtxtsideeffects.getText()*/,jtxtMedical_Centre_Ref.getText(),
            jtxtPhone1.getText(),jtxtPhone2.getText(),jtxtFax.getText(),jtxtEmail.getText(),
            jtxtPatient_NHS.getText(),jtxtEIMS_Number.getText(),jtxtGP_Appointment_ref.getText(),});
    }//GEN-LAST:event_jbtn_UpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow() == -1)
        {
            if(jTable1.getSelectedRowCount() == 0)
            {
                JOptionPane.showMessageDialog(null, "No Data to Delete", "Hospital Management Systems",
                    JOptionPane.OK_OPTION);
            }else
            {
                JOptionPane.showMessageDialog(null, "Select a row to Delete", "Hospital Management Systems",
                    JOptionPane.OK_OPTION);
            }
        }else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoctorActionPerformed
        /*Login iLogin = new Login();
        iLogin.setVisible(true);
        */
    }//GEN-LAST:event_jbtnDoctorActionPerformed

    private void jbtnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAppointmentActionPerformed
        /*Login iLogin = new Login();
        iLogin.setVisible(true);
        */
    }//GEN-LAST:event_jbtnAppointmentActionPerformed

    private void jbtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatientActionPerformed
        /*Login iLogin = new Login();
        iLogin.setVisible(true);
        */
    }//GEN-LAST:event_jbtnPatientActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed

        jComboTablets.getModel().setSelectedItem("Select Doctor's Ref.");
        jtxtDoctor_NHS.setText("");
        jtxtFirstName.setText("");
        jtxtSurName.setText("");
        jtxtMedical_Centre_Name.setText("");
        jtxtPatient_ID.setText("");
        jtxtCentre_Add.setText("");
        jtxtPost_Code.setText("");

        //jtxtsideeffects.setText("");
        jtxtMedical_Centre_Ref.setText("");
        jtxtPhone1.setText("");
        jtxtPhone2.setText("");
        jtxtFax.setText("");
        jtxtEmail.setText("");
        jtxtPatient_NHS.setText("");
        jtxtEIMS_Number.setText("");
        jtxtGP_Appointment_ref.setText("");
        //jtxtPatientAdd.setText("");
        //jtxtprescription.setText("");
        //jComboTablets.getModel().setSelectedItem("Make a Selection");

    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrescriptionActionPerformed
        /*String Qty1 = (jtxtDoctrref.getText());
        String Qty2 = (jtxtdose.getText());
        String Qty3 = (jtxttablets.getText());
        String Qty4 = (jtxtlot.getText());
        String Qty5 = (jtxtdailydose.getText());
        String Qty6 = (jtxtsideeffects.getText());
        String Qty7 = (jtxtfurtherinfo.getText());
        String Qty8 = (jtxthowtouse.getText());
        String Qty9 = (jtxtPatientID.getText());
        String Qty10 = (jtxtPatientName.getText());
        String Qty11 = (jtxtDoB.getText());
        String Qty12 = (jtxtPatientAdd.getText());
        String Qty13 = "";

        if(jComboTablets.getSelectedItem().equals("Ibuprofen"))
        {
            Qty13 = "Ibuprofen";
        }
        else if (jComboTablets.getSelectedItem().equals("Co-Codamol"))
        {
            Qty13 = "Co-Codamol";
        }
        else if (jComboTablets.getSelectedItem().equals("Paracetamol"))
        {
            Qty13 = "Paracetamol";
        }
        else if (jComboTablets.getSelectedItem().equals("Amlodopine"))
        {
            Qty13 = "Amlodopine";
        }

        jtxtprescription.setText("");
        jtxtprescription.append("\n\tHospital Management System\n\n"
            +"\nPatient Name:\t\t"+ Qty10
            +"\nDate of Birth:\t\t"+ Qty11
            +"\nPatient Address:\t"+ Qty12
            +"\nPrscription:\t\t"+ Qty13
            +"\n\n\nReference No.:\t\t"+ Qty1
            +"\nDose:\t\t"+ Qty2
            +"\nNumber of Tablets:\t"+ Qty3
            +"\nLoT:\t\t"+ Qty4
            +"\nDaily Dose:\t\t"+ Qty5
            +"\nPossible Side Effects:\t"+ Qty6
            +"\nFurther Information:\t"+ Qty7
            +"\nHow to Use Medicine:\t"+ Qty8
            +"\nPatient ID:\t\t"+ Qty9
            +"\n\n\n\n\n                       Patient Instruction we have introduced a \n\t          free text confirmation\n"
            +"                        TEXT REMINDERS FOR APPOINMENT");
*/
    }//GEN-LAST:event_jbtnPrescriptionActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        frame = new Frame();
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit.","Hospital management System",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jtxtPatient_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPatient_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPatient_IDActionPerformed

    private void jComboTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTabletsActionPerformed
        if(jComboTablets.getSelectedItem().equals("REZ10595")){
            
            jtxtDoctor_NHS.setText("Dr.RZ7855");
            jtxtFirstName.setText("Rezaur");
            jtxtSurName.setText("Rahman");
            jtxtMedical_Centre_Name.setText("Kzai Medical Centre");
            jtxtPatient_ID.setText("P8413164");
            jtxtCentre_Add.setText("Khilgaon,Dhaka");
            jtxtPost_Code.setText("1219");

            jtxtMedical_Centre_Ref.setText("RR45832");
            jtxtPhone1.setText("01638110800");
            jtxtPhone2.setText("01839100546");
            jtxtFax.setText("01638100546");
            jtxtEmail.setText("rezaur_medical@gmail.com");
            jtxtPatient_NHS.setText("Pa5434");
            jtxtEIMS_Number.setText("QR56121");
            jtxtGP_Appointment_ref.setText("YES");
        }
        else if(jComboTablets.getSelectedItem().equals("KZ10472")){
            
            jtxtDoctor_NHS.setText("Dr.KZ10544");
            jtxtFirstName.setText("Kazi");
            jtxtSurName.setText("Alam");
            jtxtMedical_Centre_Name.setText("Kazi Medical Centre");
            jtxtPatient_ID.setText("Pa4641");
            jtxtCentre_Add.setText("Khilgaon,Dhaka");
            jtxtPost_Code.setText("1219");

            jtxtMedical_Centre_Ref.setText("KA4114");
            jtxtPhone1.setText("01944637800");
            jtxtPhone2.setText("01638110140");
            jtxtFax.setText("01944110800");
            jtxtEmail.setText("kazi_medical@gmail.com");
            jtxtPatient_NHS.setText("Pa8765");
            jtxtEIMS_Number.setText("Qt41245");
            jtxtGP_Appointment_ref.setText("Yes");
        }
        else if(jComboTablets.getSelectedItem().equals("IK10474")){
            
            jtxtDoctor_NHS.setText("Dr.IK134484");
            jtxtFirstName.setText("Ibrajhim");
            jtxtSurName.setText("Khalil");
            jtxtMedical_Centre_Name.setText("Kazi Medical Centre");
            jtxtPatient_ID.setText("Pa45871");
            jtxtCentre_Add.setText("Khilgaon,Dhaka");
            jtxtPost_Code.setText("1219");

            jtxtMedical_Centre_Ref.setText("IK4114");
            jtxtPhone1.setText("0174468800");
            jtxtPhone2.setText("01538850140");
            jtxtFax.setText("01368410800");
            jtxtEmail.setText("ibrahim_medical@gmail.com");
            jtxtPatient_NHS.setText("Pa8765");
            jtxtEIMS_Number.setText("Er5584");
            jtxtGP_Appointment_ref.setText("Yes");
        }
        else if(jComboTablets.getSelectedItem().equals("SS10597")){
            
            jtxtDoctor_NHS.setText("Dr.SS10595");
            jtxtFirstName.setText("Sanzida");
            jtxtSurName.setText("Sultana");
            jtxtMedical_Centre_Name.setText("Kazi Medical Centre");
            jtxtPatient_ID.setText("Pa45674");
            jtxtCentre_Add.setText("Khilgaon,Dhaka");
            jtxtPost_Code.setText("1219");

            jtxtMedical_Centre_Ref.setText("SS4114");
            jtxtPhone1.setText("01944467800");
            jtxtPhone2.setText("01489110140");
            jtxtFax.setText("0195950800");
            jtxtEmail.setText("sanzida_medical@gmail.com");
            jtxtPatient_NHS.setText("Pa8765");
            jtxtEIMS_Number.setText("EY542");
            jtxtGP_Appointment_ref.setText("Yes");
        }
        else if(jComboTablets.getSelectedItem().equals("TI58741")){
            
            jtxtDoctor_NHS.setText("Dr.TI0178");
            jtxtFirstName.setText("Touhidul");
            jtxtSurName.setText("Islam");
            jtxtMedical_Centre_Name.setText("Kazi Medical Centre");
            jtxtPatient_ID.setText("Pa9681");
            jtxtCentre_Add.setText("Khilgaon,Dhaka");
            jtxtPost_Code.setText("1219");

            jtxtMedical_Centre_Ref.setText("TI4114");
            jtxtPhone1.setText("01864637800");
            jtxtPhone2.setText("01638110987");
            jtxtFax.setText("01944946800");
            jtxtEmail.setText("touhid_medical@gmail.com");
            jtxtPatient_NHS.setText("Pa8465");
            jtxtEIMS_Number.setText("Qp5641");
            jtxtGP_Appointment_ref.setText("Yes");
        }

    }//GEN-LAST:event_jComboTabletsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboTablets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAppointment;
    private javax.swing.JButton jbtnDoctor;
    private javax.swing.JButton jbtnPatient;
    private javax.swing.JButton jbtnPrescription;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtn_Update;
    private javax.swing.JTextField jtxtCentre_Add;
    private javax.swing.JTextField jtxtDoctor_NHS;
    private javax.swing.JTextField jtxtEIMS_Number;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFax;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtGP_Appointment_ref;
    private javax.swing.JTextField jtxtMedical_Centre_Name;
    private javax.swing.JTextField jtxtMedical_Centre_Ref;
    private javax.swing.JTextField jtxtPatient_ID;
    private javax.swing.JTextField jtxtPatient_NHS;
    private javax.swing.JTextField jtxtPhone1;
    private javax.swing.JTextField jtxtPhone2;
    private javax.swing.JTextField jtxtPost_Code;
    private javax.swing.JTextField jtxtSurName;
    // End of variables declaration//GEN-END:variables
}
